//+------------------------------------------------------------------+
//|                                     CRT_Detector_Time_Filtered.mq5 |
//|           Detects 1AM, 5AM, or 9AM Candle Range Theory           |
//|                    Based on Provided Trading Methodology         |
//+------------------------------------------------------------------+
#property copyright "Generated by AI for User"
#property link      "https://www.google.com"
#property version   "1.10"

#property indicator_chart_window
#property indicator_buffers 2
#property indicator_plots   2

// --- Plot for CRT High ---
#property indicator_label1  "CRT_High"
#property indicator_type1   DRAW_LINE
#property indicator_color1  clrDodgerBlue
#property indicator_style1  STYLE_DOT
#property indicator_width1  2

// --- Plot for CRT Low ---
#property indicator_label2  "CRT_Low"
#property indicator_type2   DRAW_LINE
#property indicator_color2  clrOrangeRed
#property indicator_style2  STYLE_DOT
#property indicator_width2  2

// --- User Inputs ---
enum ENUM_CRT_MODEL
  {
   CRT_1AM,  // 1 AM Model
   CRT_5AM,  // 5 AM Model
   CRT_9AM   // 9 AM Model
  };

input ENUM_CRT_MODEL InpModel = CRT_9AM; // Choose CRT Model to detect
input int InpNYOffset = -7;              // Your Broker Server Time vs. New York Time (e.g., -7 hours)

// --- Indicator Buffers ---
double CRTHighBuffer[];
double CRTLowBuffer[];

//+------------------------------------------------------------------+
//| Custom indicator initialization function                         |
//+------------------------------------------------------------------+
int OnInit()
  {
   SetIndexBuffer(0, CRTHighBuffer, INDICATOR_DATA);
   SetIndexBuffer(1, CRTLowBuffer, INDICATOR_DATA);
   PlotIndexSetDouble(0, PLOT_EMPTY_VALUE, EMPTY_VALUE);
   PlotIndexSetDouble(1, PLOT_EMPTY_VALUE, EMPTY_VALUE);
   PlotIndexSetString(0, PLOT_LABEL, "CRT High");
   PlotIndexSetString(1, PLOT_LABEL, "CRT Low");
   return(INIT_SUCCEEDED);
  }

//+------------------------------------------------------------------+
//| Custom indicator iteration function                              |
//+------------------------------------------------------------------+
int OnCalculate(const int rates_total,
                const int prev_calculated,
                const datetime &time[],
                const double &open[],
                const double &high[],
                const double &low[],
                const double &close[],
                const long &tick_volume[],
                const long &volume[],
                const int &spread[])
  {
   int start = rates_total - prev_calculated - 1;
   if(start < 3)
      start = 3;

   for(int i = start; i >= 1; i--)
     {
      // --- Time Filter Logic ---
      MqlDateTime dt;
      // Get the time of the Manipulation candle (the most important setup candle)
      TimeToStruct(time[i+1] + (InpNYOffset * 3600), dt);
      
      bool isKeyTime = false;
      switch(InpModel)
        {
         case CRT_1AM:
            if(dt.hour == 1) isKeyTime = true;
            break;
         case CRT_5AM:
            if(dt.hour == 5) isKeyTime = true;
            break;
         case CRT_9AM:
            if(dt.hour == 9) isKeyTime = true;
            break;
        }

      // If it's not the specific time we are looking for, skip to the next bar
      if(!isKeyTime)
         continue;

      // --- CRT Pattern Logic (Unchanged) ---
      
      // 1. Detect a Bearish CRT
      if(high[i+1] > high[i+2] && close[i+1] < high[i+2] && close[i] < open[i])
        {
         CRTHighBuffer[i]   = high[i+2];
         CRTLowBuffer[i]    = low[i+2];
         CRTHighBuffer[i+1] = high[i+2];
         CRTLowBuffer[i+1]  = low[i+2];
         CRTHighBuffer[i+2] = high[i+2];
         CRTLowBuffer[i+2]  = low[i+2];
         continue;
        }

      // 2. Detect a Bullish CRT
      if(low[i+1] < low[i+2] && close[i+1] > low[i+2] && close[i] > open[i])
        {
         CRTHighBuffer[i]   = high[i+2];
         CRTLowBuffer[i]    = low[i+2];
         CRTHighBuffer[i+1] = high[i+2];
         CRTLowBuffer[i+1]  = low[i+2];
         CRTHighBuffer[i+2] = high[i+2];
         CRTLowBuffer[i+2]  = low[i+2];
        }
     }
   return(rates_total);
  }
//+------------------------------------------------------------------+