//+------------------------------------------------------------------+
//|                             MTF_CRT_Detector_Corrected.mq5         |
//|            Detects specific H4 CRT patterns and draws lines      |
//|                    FROM THE CORRECT H4 RANGE CANDLE              |
//+------------------------------------------------------------------+
#property copyright "Generated by AI for User (Final Corrected Version)"
#property link      "https://www.google.com"
#property version   "2.00"

#property indicator_chart_window
#property indicator_buffers 0 // We will draw with objects

// --- User Inputs ---
enum ENUM_CRT_MODEL
  {
   CRT_1AM,  // 1 AM CRT Model (9PM manip, 5PM range)
   CRT_5AM,  // 5 AM CRT Model (1AM manip, 9PM range)
   CRT_9AM   // 9 AM CRT Model (5AM manip, 1AM range)
  };

input ENUM_CRT_MODEL InpModel = CRT_9AM;         // Choose CRT Model to detect
input color          InpHighColor = clrDodgerBlue; // CRT High Color
input color          InpLowColor  = clrOrangeRed; // CRT Low Color
input int            InpLineWidth = 2;           // Line Width
input int            InpNYOffset  = -7;           // IMPORTANT: Broker Server Time vs. New York Time

// --- Global variables ---
MqlRates h4Rates[];
datetime lastSignalDrawnTime = 0; // To prevent redrawing on every tick

//+------------------------------------------------------------------+
//| Custom indicator initialization function                         |
//+------------------------------------------------------------------+
int OnInit()
  {
   // Sort the H4 rates array from present to past (newest at index 0)
   ArraySetAsSeries(h4Rates, true);
   return(INIT_SUCCEEDED);
  }

//+------------------------------------------------------------------+
//| Custom indicator iteration function                              |
//+------------------------------------------------------------------+
int OnCalculate(const int rates_total,
                const int prev_calculated,
                const datetime &time[],
                const double &open[],
                const double &high[],
                const double &low[],
                const double &close[],
                const long &tick_volume[],
                const long &volume[],
                const int &spread[])
  {
   // Copy the last 100 H4 bars for our analysis
   if(CopyRates(Symbol(), PERIOD_H4, 0, 100, h4Rates) < 5)
     {
      Comment("Waiting for more H4 data...");
      return(rates_total);
     }

   // Loop through recent H4 history to find a signal
   for(int i = 1; i < 90; i++) // Check last ~15 days of H4 bars
     {
      // --- Time Filter Logic ---
      MqlDateTime dt_manipulation_candle;
      // Get time of the H4 MANIPULATION CANDLE (at index i + 1)
      TimeToStruct(h4Rates[i + 1].time + (InpNYOffset * 3600), dt_manipulation_candle);

      int keyHour = 0;
      switch(InpModel)
        {
         case CRT_1AM: keyHour = 21; break; // 9 PM
         case CRT_5AM: keyHour = 1;  break; // 1 AM
         case CRT_9AM: keyHour = 5;  break; // 5 AM
        }

      // If the manipulation candle's hour doesn't match our selected model, skip
      if(dt_manipulation_candle.hour != keyHour)
         continue;

      // This is a potential signal, check if we have already drawn it
      datetime signalConfirmationTime = h4Rates[i].time;
      if(signalConfirmationTime == lastSignalDrawnTime)
         break; // We found the most recent signal and it's already on chart, stop searching

      // --- CRT Pattern Logic ---
      // Determine the index of the range candle based on the model
      int range_candle_index = i + 2; 

      // Fetch the details of the candles
      double manip_high   = h4Rates[i+1].high;
      double manip_low    = h4Rates[i+1].low;
      double manip_close  = h4Rates[i+1].close;
      double distrib_open = h4Rates[i].open;
      double distrib_close= h4Rates[i].close;

      double range_high   = h4Rates[range_candle_index].high;
      double range_low    = h4Rates[range_candle_index].low;
      datetime range_time = h4Rates[range_candle_index].time;

      // Check for valid pattern
      bool bearishCRT = (manip_high > range_high && manip_close < range_high && distrib_close < distrib_open);
      bool bullishCRT = (manip_low < range_low && manip_close > range_low && distrib_close > distrib_open);

      if(bearishCRT || bullishCRT)
        {
         // New valid signal found, draw it and stop searching
         DrawCRTLines(range_time, range_high, range_low);
         lastSignalDrawnTime = signalConfirmationTime; // Mark as drawn
         break;
        }
     }
     
   return(rates_total);
  }

//+------------------------------------------------------------------+
//| Function to draw the CRT lines and labels                        |
//+------------------------------------------------------------------+
void DrawCRTLines(datetime startTime, double highLevel, double lowLevel)
  {
   // Clean up any old objects from the chart
   ObjectsDeleteAll(0, "CRT_");
   
   string high_line_name = "CRT_HighLine_" + (string)startTime;
   string low_line_name  = "CRT_LowLine_" + (string)startTime;
   string high_label_name = "CRT_HighLabel_" + (string)startTime;
   string low_label_name  = "CRT_LowLabel_" + (string)startTime;
   
   // --- Draw High Line ---
   ObjectCreate(0, high_line_name, OBJ_TREND, 0, startTime, highLevel, TimeCurrent(), highLevel);
   ObjectSetInteger(0, high_line_name, OBJPROP_COLOR, InpHighColor);
   ObjectSetInteger(0, high_line_name, OBJPROP_WIDTH, InpLineWidth);
   ObjectSetInteger(0, high_line_name, OBJPROP_RAY_RIGHT, true); // Extend to the right
   
   // --- Draw Low Line ---
   ObjectCreate(0, low_line_name, OBJ_TREND, 0, startTime, lowLevel, TimeCurrent(), lowLevel);
   ObjectSetInteger(0, low_line_name, OBJPROP_COLOR, InpLowColor);
   ObjectSetInteger(0, low_line_name, OBJPROP_WIDTH, InpLineWidth);
   ObjectSetInteger(0, low_line_name, OBJPROP_RAY_RIGHT, true);
   
   // --- Draw Labels ---
   string modelLabel = EnumToString(InpModel);
   StringReplace(modelLabel, "CRT_", "H4 ");
   
   ObjectCreate(0, high_label_name, OBJ_TEXT, 0, startTime, highLevel);
   ObjectSetString(0, high_label_name, OBJPROP_TEXT, modelLabel + " High");
   ObjectSetInteger(0, high_label_name, OBJPROP_COLOR, InpHighColor);
   ObjectSetInteger(0, high_label_name, OBJPROP_ANCHOR, ANCHOR_RIGHT);
   
   ObjectCreate(0, low_label_name, OBJ_TEXT, 0, startTime, lowLevel);
   ObjectSetString(0, low_label_name, OBJPROP_TEXT, modelLabel + " Low");
   ObjectSetInteger(0, low_label_name, OBJPROP_COLOR, InpLowColor);
   ObjectSetInteger(0, low_label_name, OBJPROP_ANCHOR, ANCHOR_RIGHT);
  }
//+------------------------------------------------------------------+